### PR TITLE
Add Android service.

### PR DESCRIPTION
**Pull request by hermannloose**
Merge from the `demo` branch, thus it's a little cluttered. Working Android C2DM notifications, some bug fixes and demo seeds.

### CODE REVIEW

**Comment by hermannloose** [comment]
@jupp0r: Please review. Not super urgent. :)

**Comment by hermannloose** [comment]
**NOTE:** Tests for most things are missing. Merge can be held until I've got a pull request ready for those.

**Comment by jupp0r** [comment]
Alright!

**Comment by hermannloose** [comment]
I'm getting some tests ready in [tests-for-demo-branch](https://github.com/hermannloose/escalator/tree/tests-for-demo-branch), I'll hold this pull request until then.

**Comment by hermannloose** [comment]
Merging this now, so that #29 can display the proper commit range.

**Pull request merged**
